# 미국 주식 섹터 / 서브섹터 / 종목 데이터베이스
# exchange: NASDAQ | NYSE | AMEX

US_SECTOR_MAP = {
    "AI·반도체": {
        "AI 가속기·GPU": [
            {"name": "엔비디아",              "ticker": "NVDA",  "exchange": "NASDAQ"},
            {"name": "AMD",                   "ticker": "AMD",   "exchange": "NASDAQ"},
            {"name": "브로드컴",              "ticker": "AVGO",  "exchange": "NASDAQ"},
            {"name": "마벨테크",              "ticker": "MRVL",  "exchange": "NASDAQ"},
            {"name": "퀄컴",                  "ticker": "QCOM",  "exchange": "NASDAQ"},
            {"name": "미디어텍",              "ticker": "MTC",   "exchange": "NYSE"},
            {"name": "후지쯔",                "ticker": "FJTSF", "exchange": "NYSE"},
        ],
        "AI 서버·인프라": [
            {"name": "슈퍼마이크로",          "ticker": "SMCI",  "exchange": "NASDAQ"},
            {"name": "ARM홀딩스",             "ticker": "ARM",   "exchange": "NASDAQ"},
            {"name": "아스테라랩스",          "ticker": "ALAB",  "exchange": "NASDAQ"},
            {"name": "인텔",                  "ticker": "INTC",  "exchange": "NASDAQ"},
            {"name": "델테크놀로지스",        "ticker": "DELL",  "exchange": "NYSE"},
            {"name": "HP엔터프라이즈",        "ticker": "HPE",   "exchange": "NYSE"},
            {"name": "퓨어스토리지",          "ticker": "PSTG",  "exchange": "NYSE"},
            {"name": "넷앱",                  "ticker": "NTAP",  "exchange": "NASDAQ"},
        ],
        "파운드리·EDA": [
            {"name": "TSMC",                  "ticker": "TSM",   "exchange": "NYSE"},
            {"name": "시놉시스",              "ticker": "SNPS",  "exchange": "NASDAQ"},
            {"name": "케이던스",              "ticker": "CDNS",  "exchange": "NASDAQ"},
            {"name": "글로벌파운드리",        "ticker": "GFS",   "exchange": "NASDAQ"},
            {"name": "UMC",                   "ticker": "UMC",   "exchange": "NYSE"},
        ],
        "반도체 장비": [
            {"name": "어플라이드머티어리얼즈", "ticker": "AMAT",  "exchange": "NASDAQ"},
            {"name": "램리서치",              "ticker": "LRCX",  "exchange": "NASDAQ"},
            {"name": "KLA",                   "ticker": "KLAC",  "exchange": "NASDAQ"},
            {"name": "ASML",                  "ticker": "ASML",  "exchange": "NASDAQ"},
            {"name": "테라다인",              "ticker": "TER",   "exchange": "NASDAQ"},
            {"name": "코후",                  "ticker": "COHU",  "exchange": "NASDAQ"},
            {"name": "엑셀리스",              "ticker": "XLNX",  "exchange": "NASDAQ"},
        ],
        "AI 메모리": [
            {"name": "마이크론",              "ticker": "MU",    "exchange": "NASDAQ"},
            {"name": "웨스턴디지털",          "ticker": "WDC",   "exchange": "NASDAQ"},
            {"name": "씨게이트",              "ticker": "STX",   "exchange": "NASDAQ"},
            {"name": "솔리다임(인텔NAND)",    "ticker": "INTC",  "exchange": "NASDAQ"},
        ],
        "AI 네트워킹·연결": [
            {"name": "인피니밴드(MLNX)",      "ticker": "NVDA",  "exchange": "NASDAQ"},
            {"name": "코닝",                  "ticker": "GLW",   "exchange": "NYSE"},
            {"name": "모노리식파워",          "ticker": "MPWR",  "exchange": "NASDAQ"},
            {"name": "lattice반도체",         "ticker": "LSCC",  "exchange": "NASDAQ"},
            {"name": "시러스로직",            "ticker": "CRUS",  "exchange": "NASDAQ"},
        ],
    },
    "빅테크·AI소프트": {
        "AI 플랫폼·클라우드": [
            {"name": "마이크로소프트",        "ticker": "MSFT",  "exchange": "NASDAQ"},
            {"name": "알파벳(구글)",          "ticker": "GOOGL", "exchange": "NASDAQ"},
            {"name": "아마존",                "ticker": "AMZN",  "exchange": "NASDAQ"},
            {"name": "메타",                  "ticker": "META",  "exchange": "NASDAQ"},
            {"name": "오라클",                "ticker": "ORCL",  "exchange": "NYSE"},
            {"name": "IBM",                   "ticker": "IBM",   "exchange": "NYSE"},
            {"name": "SAP",                   "ticker": "SAP",   "exchange": "NYSE"},
        ],
        "소비자 AI·기기": [
            {"name": "애플",                  "ticker": "AAPL",  "exchange": "NASDAQ"},
            {"name": "팔란티어",              "ticker": "PLTR",  "exchange": "NYSE"},
            {"name": "C3.ai",                 "ticker": "AI",    "exchange": "NYSE"},
            {"name": "사운드하운드",          "ticker": "SOUN",  "exchange": "NASDAQ"},
            {"name": "아이로봇",              "ticker": "IRBT",  "exchange": "NASDAQ"},
            {"name": "퍼시펙트(Perplexity)", "ticker": "PRPLX", "exchange": "NASDAQ"},
        ],
        "AI SaaS·엔터프라이즈": [
            {"name": "세일즈포스",            "ticker": "CRM",   "exchange": "NYSE"},
            {"name": "서비스나우",            "ticker": "NOW",   "exchange": "NYSE"},
            {"name": "스노우플레이크",        "ticker": "SNOW",  "exchange": "NYSE"},
            {"name": "워크데이",              "ticker": "WDAY",  "exchange": "NASDAQ"},
            {"name": "어도비",                "ticker": "ADBE",  "exchange": "NASDAQ"},
            {"name": "유아이패스",            "ticker": "PATH",  "exchange": "NYSE"},
            {"name": "다타독",                "ticker": "DDOG",  "exchange": "NASDAQ"},
            {"name": "몽고DB",                "ticker": "MDB",   "exchange": "NASDAQ"},
            {"name": "줌인포",                "ticker": "ZI",    "exchange": "NASDAQ"},
            {"name": "허브스팟",              "ticker": "HUBS",  "exchange": "NYSE"},
        ],
        "AI 데이터·분석": [
            {"name": "팔란티어",              "ticker": "PLTR",  "exchange": "NYSE"},
            {"name": "오픈AI(파트너)",        "ticker": "MSFT",  "exchange": "NASDAQ"},
            {"name": "어센드러닝(ALTR)",      "ticker": "ALTR",  "exchange": "NASDAQ"},
            {"name": "아나플랜",              "ticker": "PLAN",  "exchange": "NYSE"},
            {"name": "알터릭스",              "ticker": "AYX",   "exchange": "NYSE"},
            {"name": "테이블로(CRM)",         "ticker": "CRM",   "exchange": "NYSE"},
        ],
    },
    "바이오·헬스케어": {
        "신약·GLP-1": [
            {"name": "일라이릴리",            "ticker": "LLY",   "exchange": "NYSE"},
            {"name": "노보노디스크",          "ticker": "NVO",   "exchange": "NYSE"},
            {"name": "화이자",                "ticker": "PFE",   "exchange": "NYSE"},
            {"name": "머크",                  "ticker": "MRK",   "exchange": "NYSE"},
            {"name": "애브비",                "ticker": "ABBV",  "exchange": "NYSE"},
            {"name": "브리스톨마이어스",      "ticker": "BMY",   "exchange": "NYSE"},
        ],
        "mRNA·백신": [
            {"name": "모더나",                "ticker": "MRNA",  "exchange": "NASDAQ"},
            {"name": "바이오엔텍",            "ticker": "BNTX",  "exchange": "NASDAQ"},
            {"name": "노바백스",              "ticker": "NVAX",  "exchange": "NASDAQ"},
        ],
        "바이오테크": [
            {"name": "길리어드",              "ticker": "GILD",  "exchange": "NASDAQ"},
            {"name": "암젠",                  "ticker": "AMGN",  "exchange": "NASDAQ"},
            {"name": "버텍스",                "ticker": "VRTX",  "exchange": "NASDAQ"},
            {"name": "리제네론",              "ticker": "REGN",  "exchange": "NASDAQ"},
            {"name": "바이오젠",              "ticker": "BIIB",  "exchange": "NASDAQ"},
        ],
        "의료기기·수술로봇": [
            {"name": "인튜이티브서지컬",      "ticker": "ISRG",  "exchange": "NASDAQ"},
            {"name": "애보트",                "ticker": "ABT",   "exchange": "NYSE"},
            {"name": "메드트로닉",            "ticker": "MDT",   "exchange": "NYSE"},
            {"name": "덱스콤",                "ticker": "DXCM",  "exchange": "NASDAQ"},
            {"name": "스트라이커",            "ticker": "SYK",   "exchange": "NYSE"},
        ],
        "헬스케어 보험": [
            {"name": "유나이티드헬스",        "ticker": "UNH",   "exchange": "NYSE"},
            {"name": "CVS헬스",               "ticker": "CVS",   "exchange": "NYSE"},
            {"name": "시그나",                "ticker": "CI",    "exchange": "NYSE"},
            {"name": "험비",                  "ticker": "HUM",   "exchange": "NYSE"},
        ],
    },
    "방산·우주": {
        "전통 방산": [
            {"name": "록히드마틴",            "ticker": "LMT",   "exchange": "NYSE"},
            {"name": "레이시온",              "ticker": "RTX",   "exchange": "NYSE"},
            {"name": "노스롭그루먼",          "ticker": "NOC",   "exchange": "NYSE"},
            {"name": "제너럴다이내믹스",      "ticker": "GD",    "exchange": "NYSE"},
            {"name": "L3해리스",              "ticker": "LHX",   "exchange": "NYSE"},
        ],
        "우주·발사체": [
            {"name": "로켓랩",                "ticker": "RKLB",  "exchange": "NASDAQ"},
            {"name": "인튜이티브머신스",      "ticker": "LUNR",  "exchange": "NASDAQ"},
            {"name": "버진갤럭틱",            "ticker": "SPCE",  "exchange": "NYSE"},
        ],
        "드론·무인기": [
            {"name": "AeroVironment",         "ticker": "AVAV",  "exchange": "NASDAQ"},
            {"name": "텍스트론",              "ticker": "TXT",   "exchange": "NYSE"},
            {"name": "Shield AI(SHLD)",       "ticker": "SHLD",  "exchange": "NYSE"},
        ],
        "사이버·전자전": [
            {"name": "CACI인터내셔널",        "ticker": "CACI",  "exchange": "NYSE"},
            {"name": "부즈앨런해밀턴",        "ticker": "BAH",   "exchange": "NYSE"},
            {"name": "레이도스홀딩스",        "ticker": "LDOS",  "exchange": "NYSE"},
        ],
    },
    "사이버보안": {
        "엔드포인트 보안": [
            {"name": "크라우드스트라이크",    "ticker": "CRWD",  "exchange": "NASDAQ"},
            {"name": "센티넬원",              "ticker": "S",     "exchange": "NYSE"},
            {"name": "팔로알토",              "ticker": "PANW",  "exchange": "NASDAQ"},
            {"name": "래피드7",               "ticker": "RPD",   "exchange": "NASDAQ"},
            {"name": "바로니스",              "ticker": "VRNS",  "exchange": "NASDAQ"},
            {"name": "카보나이트(오픈텍스트)","ticker": "OTEX",  "exchange": "NASDAQ"},
            {"name": "트렌드마이크로",        "ticker": "TMICY", "exchange": "NYSE"},
        ],
        "클라우드·제로트러스트": [
            {"name": "지스케일러",            "ticker": "ZS",    "exchange": "NASDAQ"},
            {"name": "포티넷",                "ticker": "FTNT",  "exchange": "NASDAQ"},
            {"name": "옥타",                  "ticker": "OKTA",  "exchange": "NASDAQ"},
            {"name": "사이버아크",            "ticker": "CYBR",  "exchange": "NASDAQ"},
            {"name": "클라우드플레어",        "ticker": "NET",   "exchange": "NYSE"},
            {"name": "일루미오",              "ticker": "ILLM",  "exchange": "NASDAQ"},
            {"name": "엑스트라홉",           "ticker": "EXHD",  "exchange": "NASDAQ"},
        ],
        "네트워크 보안": [
            {"name": "체크포인트",            "ticker": "CHKP",  "exchange": "NASDAQ"},
            {"name": "테너블",                "ticker": "TENB",  "exchange": "NASDAQ"},
            {"name": "퀄리스",                "ticker": "QLYS",  "exchange": "NASDAQ"},
            {"name": "F5네트웍스",            "ticker": "FFIV",  "exchange": "NASDAQ"},
            {"name": "래드웨어",              "ticker": "RDWR",  "exchange": "NASDAQ"},
            {"name": "이그나이트(팔로알토)", "ticker": "PANW",  "exchange": "NASDAQ"},
        ],
        "ID·인증 보안": [
            {"name": "SailPoint",             "ticker": "SAIL",  "exchange": "NYSE"},
            {"name": "핑아이덴티티",          "ticker": "PING",  "exchange": "NYSE"},
            {"name": "베욘드트러스트",        "ticker": "BTGI",  "exchange": "NYSE"},
            {"name": "포그록(FROG)",          "ticker": "FROG",  "exchange": "NASDAQ"},
            {"name": "원로그인",              "ticker": "OL",    "exchange": "NASDAQ"},
        ],
        "위협 인텔리전스·SIEM": [
            {"name": "엘라스틱",              "ticker": "ESTC",  "exchange": "NYSE"},
            {"name": "다이나트레이스",        "ticker": "DT",    "exchange": "NYSE"},
            {"name": "로그리듬",              "ticker": "LOGR",  "exchange": "NASDAQ"},
            {"name": "시큐어웍스",            "ticker": "SCWX",  "exchange": "NASDAQ"},
            {"name": "IBM(보안부문)",         "ticker": "IBM",   "exchange": "NYSE"},
        ],
        "데이터·클라우드 보안": [
            {"name": "루브릭",                "ticker": "RBRK",  "exchange": "NYSE"},
            {"name": "다크트레이스",          "ticker": "DARK",  "exchange": "NASDAQ"},
            {"name": "코그나이트",            "ticker": "CGNT",  "exchange": "NASDAQ"},
            {"name": "아크로니스(공개전)",    "ticker": "ACRO",  "exchange": "NASDAQ"},
            {"name": "솔라윈즈",              "ticker": "SWI",   "exchange": "NYSE"},
        ],
    },
    "양자컴퓨터·암호": {
        "순수 양자컴퓨팅": [
            {"name": "IonQ",                  "ticker": "IONQ",  "exchange": "NYSE"},
            {"name": "D-Wave Quantum",         "ticker": "QBTS",  "exchange": "NYSE"},
            {"name": "Rigetti Computing",      "ticker": "RGTI",  "exchange": "NASDAQ"},
            {"name": "Quantum Computing Inc",  "ticker": "QUBT",  "exchange": "NASDAQ"},
            {"name": "Arqit Quantum",          "ticker": "ARQQ",  "exchange": "NASDAQ"},
            {"name": "QuantumComputingInc",    "ticker": "QUBT",  "exchange": "NASDAQ"},
        ],
        "빅테크 양자 투자": [
            {"name": "IBM(Quantum)",           "ticker": "IBM",   "exchange": "NYSE"},
            {"name": "알파벳(Google Quantum)", "ticker": "GOOGL", "exchange": "NASDAQ"},
            {"name": "마이크로소프트(Azure Q)","ticker": "MSFT",  "exchange": "NASDAQ"},
            {"name": "인텔(실리콘 양자)",      "ticker": "INTC",  "exchange": "NASDAQ"},
            {"name": "하니웰(Quantinuum)",     "ticker": "HON",   "exchange": "NASDAQ"},
            {"name": "아마존(Braket)",         "ticker": "AMZN",  "exchange": "NASDAQ"},
        ],
        "양자 소재·광자": [
            {"name": "코닝(광섬유)",           "ticker": "GLW",   "exchange": "NYSE"},
            {"name": "II-VI(COHERENT)",        "ticker": "COHR",  "exchange": "NYSE"},
            {"name": "루멘텀",                 "ticker": "LITE",  "exchange": "NASDAQ"},
            {"name": "MKS인스트루먼트",        "ticker": "MKSI",  "exchange": "NASDAQ"},
        ],
        "양자 암호·보안": [
            {"name": "Arqit Quantum",          "ticker": "ARQQ",  "exchange": "NASDAQ"},
            {"name": "Quantinuum(HON)",        "ticker": "HON",   "exchange": "NASDAQ"},
            {"name": "PQ쉴드(비상장)",         "ticker": "PQSH",  "exchange": "NASDAQ"},
            {"name": "퀀텀엑스체인지",         "ticker": "QXCH",  "exchange": "NASDAQ"},
        ],
    },
    "에너지·원자력": {
        "원자력·우라늄": [
            {"name": "카메코",                "ticker": "CCJ",   "exchange": "NYSE"},
            {"name": "컨스텔레이션에너지",    "ticker": "CEG",   "exchange": "NASDAQ"},
            {"name": "비스트라",              "ticker": "VST",   "exchange": "NYSE"},
            {"name": "NuScale",               "ticker": "SMR",   "exchange": "NYSE"},
        ],
        "천연가스·LNG": [
            {"name": "셰니어에너지",          "ticker": "LNG",   "exchange": "NYSE"},
            {"name": "EQT",                   "ticker": "EQT",   "exchange": "NYSE"},
            {"name": "코테라에너지",          "ticker": "CTRA",  "exchange": "NYSE"},
        ],
        "재생에너지": [
            {"name": "인페이즈에너지",        "ticker": "ENPH",  "exchange": "NASDAQ"},
            {"name": "퍼스트솔라",            "ticker": "FSLR",  "exchange": "NASDAQ"},
            {"name": "넥스트에라에너지",      "ticker": "NEE",   "exchange": "NYSE"},
            {"name": "선런",                  "ticker": "RUN",   "exchange": "NASDAQ"},
        ],
        "빅오일": [
            {"name": "엑슨모빌",              "ticker": "XOM",   "exchange": "NYSE"},
            {"name": "셰브론",                "ticker": "CVX",   "exchange": "NYSE"},
            {"name": "옥시덴탈",              "ticker": "OXY",   "exchange": "NYSE"},
            {"name": "코노코필립스",          "ticker": "COP",   "exchange": "NYSE"},
        ],
    },
    "금융·핀테크": {
        "빅뱅크": [
            {"name": "JP모건",                "ticker": "JPM",   "exchange": "NYSE"},
            {"name": "뱅크오브아메리카",      "ticker": "BAC",   "exchange": "NYSE"},
            {"name": "골드만삭스",            "ticker": "GS",    "exchange": "NYSE"},
            {"name": "모건스탠리",            "ticker": "MS",    "exchange": "NYSE"},
            {"name": "웰스파고",              "ticker": "WFC",   "exchange": "NYSE"},
            {"name": "씨티그룹",              "ticker": "C",     "exchange": "NYSE"},
        ],
        "핀테크·결제": [
            {"name": "비자",                  "ticker": "V",     "exchange": "NYSE"},
            {"name": "마스터카드",            "ticker": "MA",    "exchange": "NYSE"},
            {"name": "페이팔",                "ticker": "PYPL",  "exchange": "NASDAQ"},
            {"name": "블록(스퀘어)",          "ticker": "SQ",    "exchange": "NYSE"},
            {"name": "어펌",                  "ticker": "AFRM",  "exchange": "NASDAQ"},
            {"name": "소파이",                "ticker": "SOFI",  "exchange": "NASDAQ"},
        ],
        "암호화폐·블록체인": [
            {"name": "코인베이스",            "ticker": "COIN",  "exchange": "NASDAQ"},
            {"name": "마이크로스트래티지",    "ticker": "MSTR",  "exchange": "NASDAQ"},
            {"name": "로빈후드",              "ticker": "HOOD",  "exchange": "NASDAQ"},
        ],
        "자산운용·보험": [
            {"name": "버크셔해서웨이",        "ticker": "BRK-B", "exchange": "NYSE"},
            {"name": "블랙록",                "ticker": "BLK",   "exchange": "NYSE"},
            {"name": "찰스슈왑",              "ticker": "SCHW",  "exchange": "NYSE"},
            {"name": "아메리칸익스프레스",    "ticker": "AXP",   "exchange": "NYSE"},
        ],
    },
    "EV·로봇·자율주행": {
        "EV 완성차": [
            {"name": "테슬라",                "ticker": "TSLA",  "exchange": "NASDAQ"},
            {"name": "리비안",                "ticker": "RIVN",  "exchange": "NASDAQ"},
            {"name": "루시드",                "ticker": "LCID",  "exchange": "NASDAQ"},
            {"name": "니오",                  "ticker": "NIO",   "exchange": "NYSE"},
        ],
        "EV 부품·충전": [
            {"name": "온세미컨덕터",          "ticker": "ON",    "exchange": "NASDAQ"},
            {"name": "차지포인트",            "ticker": "CHPT",  "exchange": "NYSE"},
            {"name": "블링크차징",            "ticker": "BLNK",  "exchange": "NASDAQ"},
            {"name": "BorgWarner",            "ticker": "BWA",   "exchange": "NYSE"},
        ],
        "인간형 로봇·AI 하드웨어": [
            {"name": "테슬라(옵티머스)",      "ticker": "TSLA",  "exchange": "NASDAQ"},
            {"name": "ABB(로봇부문)",         "ticker": "ABB",   "exchange": "NYSE"},
            {"name": "하니웰",                "ticker": "HON",   "exchange": "NASDAQ"},
        ],
        "자율주행·라이다": [
            {"name": "모빌아이",              "ticker": "MBLY",  "exchange": "NASDAQ"},
            {"name": "루미나테크",            "ticker": "LAZR",  "exchange": "NASDAQ"},
            {"name": "우버",                  "ticker": "UBER",  "exchange": "NYSE"},
        ],
    },
    "소비재·유통": {
        "이커머스·소매": [
            {"name": "아마존",                "ticker": "AMZN",  "exchange": "NASDAQ"},
            {"name": "쇼피파이",              "ticker": "SHOP",  "exchange": "NYSE"},
            {"name": "이베이",                "ticker": "EBAY",  "exchange": "NASDAQ"},
            {"name": "엣시",                  "ticker": "ETSY",  "exchange": "NASDAQ"},
        ],
        "오프라인 유통": [
            {"name": "월마트",                "ticker": "WMT",   "exchange": "NYSE"},
            {"name": "코스트코",              "ticker": "COST",  "exchange": "NASDAQ"},
            {"name": "타겟",                  "ticker": "TGT",   "exchange": "NYSE"},
            {"name": "홈디포",                "ticker": "HD",    "exchange": "NYSE"},
            {"name": "달러제너럴",            "ticker": "DG",    "exchange": "NYSE"},
        ],
        "명품·패션·스포츠": [
            {"name": "나이키",                "ticker": "NKE",   "exchange": "NYSE"},
            {"name": "언더아머",              "ticker": "UA",    "exchange": "NYSE"},
            {"name": "룰루레몬",              "ticker": "LULU",  "exchange": "NASDAQ"},
            {"name": "PVH(CK·타미)",          "ticker": "PVH",   "exchange": "NYSE"},
        ],
        "필수 소비재": [
            {"name": "프록터앤갬블",          "ticker": "PG",    "exchange": "NYSE"},
            {"name": "코카콜라",              "ticker": "KO",    "exchange": "NYSE"},
            {"name": "펩시코",                "ticker": "PEP",   "exchange": "NASDAQ"},
            {"name": "콜게이트",              "ticker": "CL",    "exchange": "NYSE"},
            {"name": "유니레버",              "ticker": "UL",    "exchange": "NYSE"},
        ],
        "음식·외식": [
            {"name": "맥도날드",              "ticker": "MCD",   "exchange": "NYSE"},
            {"name": "스타벅스",              "ticker": "SBUX",  "exchange": "NASDAQ"},
            {"name": "치폴레",                "ticker": "CMG",   "exchange": "NYSE"},
            {"name": "얌브랜즈(KFC·피자헛)", "ticker": "YUM",   "exchange": "NYSE"},
        ],
    },
    "미디어·엔터·게임": {
        "스트리밍·OTT": [
            {"name": "넷플릭스",              "ticker": "NFLX",  "exchange": "NASDAQ"},
            {"name": "디즈니",                "ticker": "DIS",   "exchange": "NYSE"},
            {"name": "워너브라더스",          "ticker": "WBD",   "exchange": "NASDAQ"},
            {"name": "파라마운트",            "ticker": "PARA",  "exchange": "NASDAQ"},
        ],
        "음악·팟캐스트": [
            {"name": "스포티파이",            "ticker": "SPOT",  "exchange": "NYSE"},
            {"name": "라이브네이션",          "ticker": "LYV",   "exchange": "NYSE"},
        ],
        "게임·메타버스": [
            {"name": "로블록스",              "ticker": "RBLX",  "exchange": "NYSE"},
            {"name": "일렉트로닉아츠",        "ticker": "EA",    "exchange": "NASDAQ"},
            {"name": "테이크투인터랙티브",    "ticker": "TTWO",  "exchange": "NASDAQ"},
            {"name": "유니티소프트웨어",      "ticker": "U",     "exchange": "NYSE"},
            {"name": "액티비전(MSFT)",        "ticker": "MSFT",  "exchange": "NASDAQ"},
        ],
        "광고·디지털미디어": [
            {"name": "트레이드데스크",        "ticker": "TTD",   "exchange": "NASDAQ"},
            {"name": "퍼블리시스",            "ticker": "PUBGY", "exchange": "NYSE"},
            {"name": "IPG",                   "ticker": "IPG",   "exchange": "NYSE"},
        ],
    },
    "통신·네트워크": {
        "이동통신": [
            {"name": "T-모바일",              "ticker": "TMUS",  "exchange": "NASDAQ"},
            {"name": "버라이즌",              "ticker": "VZ",    "exchange": "NYSE"},
            {"name": "AT&T",                  "ticker": "T",     "exchange": "NYSE"},
        ],
        "위성·저궤도(LEO)": [
            {"name": "버진갤럭틱",            "ticker": "SPCE",  "exchange": "NYSE"},
            {"name": "비아샛",                "ticker": "VSAT",  "exchange": "NASDAQ"},
            {"name": "글로벌스타",            "ticker": "GSAT",  "exchange": "NYSE"},
        ],
        "케이블·인터넷": [
            {"name": "컴캐스트",              "ticker": "CMCSA", "exchange": "NASDAQ"},
            {"name": "차터커뮤니케이션",      "ticker": "CHTR",  "exchange": "NASDAQ"},
            {"name": "알티스",                "ticker": "ATUS",  "exchange": "NASDAQ"},
        ],
        "네트워크 장비": [
            {"name": "시스코",                "ticker": "CSCO",  "exchange": "NASDAQ"},
            {"name": "주니퍼네트웍스",        "ticker": "JNPR",  "exchange": "NYSE"},
            {"name": "아리스타네트웍스",      "ticker": "ANET",  "exchange": "NYSE"},
        ],
    },
    "항공·여행·관광": {
        "항공사": [
            {"name": "델타항공",              "ticker": "DAL",   "exchange": "NYSE"},
            {"name": "유나이티드항공",        "ticker": "UAL",   "exchange": "NASDAQ"},
            {"name": "아메리칸항공",          "ticker": "AAL",   "exchange": "NASDAQ"},
            {"name": "사우스웨스트항공",      "ticker": "LUV",   "exchange": "NYSE"},
        ],
        "온라인 여행": [
            {"name": "부킹홀딩스",            "ticker": "BKNG",  "exchange": "NASDAQ"},
            {"name": "에어비앤비",            "ticker": "ABNB",  "exchange": "NASDAQ"},
            {"name": "익스피디아",            "ticker": "EXPE",  "exchange": "NASDAQ"},
            {"name": "트립어드바이저",        "ticker": "TRIP",  "exchange": "NASDAQ"},
        ],
        "크루즈·호텔": [
            {"name": "카니발크루즈",          "ticker": "CCL",   "exchange": "NYSE"},
            {"name": "로열캐리비안",          "ticker": "RCL",   "exchange": "NYSE"},
            {"name": "힐튼호텔",              "ticker": "HLT",   "exchange": "NYSE"},
            {"name": "메리어트",              "ticker": "MAR",   "exchange": "NASDAQ"},
        ],
    },
    "리츠·부동산": {
        "데이터센터 리츠": [
            {"name": "에퀴닉스",              "ticker": "EQIX",  "exchange": "NASDAQ"},
            {"name": "디지털리얼티",          "ticker": "DLR",   "exchange": "NYSE"},
            {"name": "아이언마운틴",          "ticker": "IRM",   "exchange": "NYSE"},
        ],
        "물류·인프라 리츠": [
            {"name": "프롤로지스",            "ticker": "PLD",   "exchange": "NYSE"},
            {"name": "아메리칸타워",          "ticker": "AMT",   "exchange": "NYSE"},
            {"name": "크라운캐슬",            "ticker": "CCI",   "exchange": "NYSE"},
        ],
        "주거·상업 리츠": [
            {"name": "사이먼프로퍼티",        "ticker": "SPG",   "exchange": "NYSE"},
            {"name": "리얼티인컴",            "ticker": "O",     "exchange": "NYSE"},
            {"name": "아발론베이",            "ticker": "AVB",   "exchange": "NYSE"},
        ],
    },
    "전통 산업·소재": {
        "철강·금속": [
            {"name": "뉴코어",                "ticker": "NUE",   "exchange": "NYSE"},
            {"name": "US스틸",                "ticker": "X",     "exchange": "NYSE"},
            {"name": "프리포트맥모란(구리)",  "ticker": "FCX",   "exchange": "NYSE"},
        ],
        "화학·소재": [
            {"name": "다우",                  "ticker": "DOW",   "exchange": "NYSE"},
            {"name": "듀폰",                  "ticker": "DD",    "exchange": "NYSE"},
            {"name": "에어프로덕츠",          "ticker": "APD",   "exchange": "NYSE"},
        ],
        "건설·인프라": [
            {"name": "캐터필러",              "ticker": "CAT",   "exchange": "NYSE"},
            {"name": "디어앤컴퍼니",          "ticker": "DE",    "exchange": "NYSE"},
            {"name": "불캔머티어리얼스",      "ticker": "VMC",   "exchange": "NYSE"},
        ],
        "자동차·전통 완성차": [
            {"name": "포드",                  "ticker": "F",     "exchange": "NYSE"},
            {"name": "GM",                    "ticker": "GM",    "exchange": "NYSE"},
            {"name": "스텔란티스",            "ticker": "STLA",  "exchange": "NYSE"},
        ],
    },
}
