# 국내 주식 섹터 / 서브섹터 / 종목 데이터베이스
# suffix: .KS = KOSPI, .KQ = KOSDAQ

KR_SECTOR_MAP = {
    "반도체": {
        "반도체 공정": [
            {"name": "삼성전자",       "code": "005930", "suffix": ".KS"},
            {"name": "SK하이닉스",     "code": "000660", "suffix": ".KS"},
            {"name": "DB하이텍",       "code": "000990", "suffix": ".KS"},
            {"name": "LG이노텍",       "code": "011070", "suffix": ".KS"},
            {"name": "원익홀딩스",     "code": "032940", "suffix": ".KQ"},
            {"name": "SK스퀘어",       "code": "402340", "suffix": ".KS"},
        ],
        "HBM·메모리": [
            {"name": "SK하이닉스",     "code": "000660", "suffix": ".KS"},
            {"name": "한미반도체",     "code": "042700", "suffix": ".KQ"},
            {"name": "HPSP",          "code": "403870", "suffix": ".KQ"},
            {"name": "이오테크닉스",   "code": "039030", "suffix": ".KQ"},
            {"name": "테스",          "code": "095610", "suffix": ".KQ"},
            {"name": "기가레인",       "code": "049080", "suffix": ".KQ"},
            {"name": "에스에프에이",   "code": "056190", "suffix": ".KQ"},
        ],
        "유리기판·PCB": [
            {"name": "삼성전기",       "code": "009150", "suffix": ".KS"},
            {"name": "이수페타시스",   "code": "007660", "suffix": ".KS"},
            {"name": "심텍",          "code": "222800", "suffix": ".KQ"},
            {"name": "코리아써키트",   "code": "007810", "suffix": ".KS"},
            {"name": "대덕전자",       "code": "008060", "suffix": ".KS"},
            {"name": "인터플렉스",     "code": "051370", "suffix": ".KQ"},
            {"name": "뉴프렉스",       "code": "085670", "suffix": ".KQ"},
            {"name": "SI플렉스",       "code": "148490", "suffix": ".KQ"},
        ],
        "반도체 소재": [
            {"name": "솔브레인",       "code": "357780", "suffix": ".KQ"},
            {"name": "동진쎄미켐",     "code": "005290", "suffix": ".KS"},
            {"name": "한솔케미칼",     "code": "014680", "suffix": ".KS"},
            {"name": "원익머트리얼즈", "code": "104830", "suffix": ".KQ"},
            {"name": "덕산네오룩스",   "code": "213420", "suffix": ".KQ"},
            {"name": "이엔에프테크놀로지","code": "102710", "suffix": ".KQ"},
            {"name": "솔루스첨단소재", "code": "336370", "suffix": ".KQ"},
            {"name": "후성",          "code": "093370", "suffix": ".KQ"},
        ],
        "반도체 장비": [
            {"name": "원익IPS",        "code": "240810", "suffix": ".KQ"},
            {"name": "주성엔지니어링", "code": "036930", "suffix": ".KQ"},
            {"name": "피에스케이",     "code": "319660", "suffix": ".KQ"},
            {"name": "유진테크",       "code": "084370", "suffix": ".KQ"},
            {"name": "파크시스템스",   "code": "140860", "suffix": ".KQ"},
            {"name": "고영",          "code": "098460", "suffix": ".KQ"},
            {"name": "인텍플러스",     "code": "064290", "suffix": ".KQ"},
            {"name": "한양이엔지",     "code": "045590", "suffix": ".KQ"},
            {"name": "티씨케이",       "code": "064760", "suffix": ".KQ"},
        ],
        "반도체 패키징": [
            {"name": "한미반도체",     "code": "042700", "suffix": ".KQ"},
            {"name": "두산테스나",     "code": "131970", "suffix": ".KQ"},
            {"name": "SFA반도체",      "code": "036540", "suffix": ".KQ"},
            {"name": "네패스",         "code": "033640", "suffix": ".KQ"},
            {"name": "하나마이크론",   "code": "067310", "suffix": ".KQ"},
            {"name": "ISC",           "code": "095340", "suffix": ".KQ"},
            {"name": "테크윙",         "code": "089030", "suffix": ".KQ"},
        ],
    },
    "2차전지": {
        "배터리 셀": [
            {"name": "LG에너지솔루션", "code": "373220", "suffix": ".KS"},
            {"name": "삼성SDI",        "code": "006400", "suffix": ".KS"},
            {"name": "SK이노베이션",   "code": "096770", "suffix": ".KS"},
            {"name": "에코프로",       "code": "086520", "suffix": ".KQ"},
        ],
        "양극재": [
            {"name": "에코프로비엠",   "code": "247540", "suffix": ".KQ"},
            {"name": "포스코퓨처엠",   "code": "003670", "suffix": ".KS"},
            {"name": "엘앤에프",       "code": "066970", "suffix": ".KQ"},
            {"name": "코스모신소재",   "code": "005070", "suffix": ".KS"},
            {"name": "에코프로",       "code": "086520", "suffix": ".KQ"},
            {"name": "코스모화학",     "code": "005420", "suffix": ".KS"},
            {"name": "엠케이전자",     "code": "033920", "suffix": ".KQ"},
        ],
        "음극재": [
            {"name": "포스코홀딩스",   "code": "005490", "suffix": ".KS"},
            {"name": "대주전자재료",   "code": "078600", "suffix": ".KQ"},
            {"name": "일진머티리얼즈", "code": "020150", "suffix": ".KS"},
            {"name": "한솔케미칼",     "code": "014680", "suffix": ".KS"},
            {"name": "솔루에타",       "code": "357780", "suffix": ".KQ"},
        ],
        "전해질·분리막": [
            {"name": "솔브레인홀딩스", "code": "036830", "suffix": ".KQ"},
            {"name": "SK아이이테크",   "code": "361610", "suffix": ".KS"},
            {"name": "더블유씨피",     "code": "393890", "suffix": ".KQ"},
            {"name": "리켐",          "code": "131290", "suffix": ".KQ"},
            {"name": "엔켐",          "code": "348370", "suffix": ".KQ"},
            {"name": "동화기업",       "code": "025900", "suffix": ".KS"},
        ],
        "전지 장비·부품": [
            {"name": "피엔티",         "code": "137400", "suffix": ".KQ"},
            {"name": "씨아이에스",     "code": "222080", "suffix": ".KQ"},
            {"name": "엠플러스",       "code": "259630", "suffix": ".KQ"},
            {"name": "하나기술",       "code": "299030", "suffix": ".KQ"},
            {"name": "코윈테크",       "code": "282880", "suffix": ".KQ"},
            {"name": "나라엠앤디",     "code": "051310", "suffix": ".KQ"},
            {"name": "상신이디피",     "code": "091580", "suffix": ".KQ"},
        ],
    },
    "바이오·제약": {
        "신약 개발": [
            {"name": "셀트리온",       "code": "068270", "suffix": ".KS"},
            {"name": "유한양행",       "code": "000100", "suffix": ".KS"},
            {"name": "한미약품",       "code": "128940", "suffix": ".KS"},
            {"name": "HLB",           "code": "028300", "suffix": ".KQ"},
            {"name": "녹십자",         "code": "006280", "suffix": ".KS"},
            {"name": "종근당",         "code": "185750", "suffix": ".KS"},
            {"name": "동아에스티",     "code": "170900", "suffix": ".KS"},
            {"name": "보령",          "code": "003850", "suffix": ".KS"},
            {"name": "대웅제약",       "code": "069620", "suffix": ".KQ"},
            {"name": "일동제약",       "code": "249420", "suffix": ".KS"},
        ],
        "바이오벤처·신약": [
            {"name": "에이비엘바이오", "code": "298380", "suffix": ".KQ"},
            {"name": "알테오젠",       "code": "196170", "suffix": ".KQ"},
            {"name": "HLB생명과학",    "code": "067630", "suffix": ".KQ"},
            {"name": "제넥신",         "code": "095700", "suffix": ".KQ"},
            {"name": "메디톡스",       "code": "086900", "suffix": ".KQ"},
            {"name": "SK바이오팜",     "code": "326030", "suffix": ".KS"},
            {"name": "유바이오로직스", "code": "206650", "suffix": ".KQ"},
            {"name": "올릭스",         "code": "226950", "suffix": ".KQ"},
        ],
        "의료기기": [
            {"name": "오스템임플란트", "code": "048260", "suffix": ".KQ"},
            {"name": "바텍",          "code": "043150", "suffix": ".KQ"},
            {"name": "인바디",         "code": "041830", "suffix": ".KQ"},
            {"name": "루닛",          "code": "328130", "suffix": ".KQ"},
            {"name": "뷰노",          "code": "338220", "suffix": ".KQ"},
            {"name": "클래시스",       "code": "214150", "suffix": ".KQ"},
            {"name": "제이시스메디칼", "code": "287410", "suffix": ".KQ"},
            {"name": "솔루엠",         "code": "357880", "suffix": ".KQ"},
        ],
        "CMO 위탁생산": [
            {"name": "삼성바이오로직스","code": "207940", "suffix": ".KS"},
            {"name": "에스티팜",       "code": "237690", "suffix": ".KQ"},
            {"name": "바이넥스",       "code": "053030", "suffix": ".KQ"},
            {"name": "SK바이오사이언스","code": "302440", "suffix": ".KS"},
            {"name": "동아소시오홀딩스","code": "000640", "suffix": ".KS"},
        ],
        "진단·헬스케어": [
            {"name": "씨젠",          "code": "096530", "suffix": ".KQ"},
            {"name": "레고켐바이오",   "code": "141080", "suffix": ".KQ"},
            {"name": "오리온홀딩스",   "code": "001800", "suffix": ".KS"},
            {"name": "셀바스AI",       "code": "108860", "suffix": ".KQ"},
            {"name": "인성정보",       "code": "033230", "suffix": ".KQ"},
        ],
    },
    "AI·로봇": {
        "AI 플랫폼": [
            {"name": "NAVER",         "code": "035420", "suffix": ".KS"},
            {"name": "카카오",         "code": "035720", "suffix": ".KS"},
            {"name": "크래프톤",       "code": "259960", "suffix": ".KS"},
            {"name": "삼성SDS",        "code": "018260", "suffix": ".KS"},
            {"name": "더존비즈온",     "code": "012510", "suffix": ".KQ"},
            {"name": "솔트룩스",       "code": "304100", "suffix": ".KQ"},
            {"name": "코난테크놀로지", "code": "402030", "suffix": ".KQ"},
            {"name": "마인즈랩",       "code": "377480", "suffix": ".KQ"},
        ],
        "AI 반도체·NPU": [
            {"name": "리노공업",       "code": "058470", "suffix": ".KQ"},
            {"name": "오픈엣지테크",   "code": "394730", "suffix": ".KQ"},
            {"name": "파두",          "code": "440110", "suffix": ".KQ"},
            {"name": "넥스트칩",       "code": "040350", "suffix": ".KQ"},
            {"name": "퓨런티어",       "code": "370090", "suffix": ".KQ"},
        ],
        "AI 데이터센터": [
            {"name": "삼성SDS",        "code": "018260", "suffix": ".KS"},
            {"name": "SK C&C",         "code": "034730", "suffix": ".KS"},
            {"name": "케이아이엔엑스",  "code": "093320", "suffix": ".KQ"},
            {"name": "가비아",         "code": "079940", "suffix": ".KQ"},
            {"name": "아이마켓코리아", "code": "122900", "suffix": ".KQ"},
        ],
        "로봇": [
            {"name": "두산로보틱스",   "code": "454910", "suffix": ".KS"},
            {"name": "레인보우로보틱스","code": "277810", "suffix": ".KQ"},
            {"name": "현대로보틱스",   "code": "267270", "suffix": ".KS"},
            {"name": "티로보틱스",     "code": "117730", "suffix": ".KQ"},
            {"name": "뉴로메카",       "code": "348340", "suffix": ".KQ"},
            {"name": "로보스타",       "code": "090360", "suffix": ".KQ"},
            {"name": "에스비비테크",   "code": "389650", "suffix": ".KQ"},
            {"name": "유진로봇",       "code": "056080", "suffix": ".KQ"},
            {"name": "한화에어로스페이스","code": "012450", "suffix": ".KS"},
        ],
        "자율주행·전장": [
            {"name": "현대모비스",     "code": "012330", "suffix": ".KS"},
            {"name": "HL만도",         "code": "204320", "suffix": ".KS"},
            {"name": "현대오토에버",   "code": "307950", "suffix": ".KS"},
            {"name": "아이나비시스템즈","code": "068360", "suffix": ".KQ"},
            {"name": "모트렉스",       "code": "118990", "suffix": ".KQ"},
            {"name": "픽셀플러스",     "code": "087600", "suffix": ".KQ"},
        ],
    },
    "방산": {
        "육상무기·장갑차": [
            {"name": "한화에어로스페이스","code": "012450", "suffix": ".KS"},
            {"name": "현대로템",       "code": "064350", "suffix": ".KS"},
            {"name": "LIG넥스원",      "code": "079550", "suffix": ".KS"},
            {"name": "한화",          "code": "000880", "suffix": ".KS"},
            {"name": "풍산",          "code": "103140", "suffix": ".KS"},
            {"name": "SNT다이내믹스",  "code": "003570", "suffix": ".KS"},
            {"name": "한국화약(한화)", "code": "000880", "suffix": ".KS"},
        ],
        "항공·우주": [
            {"name": "한국항공우주",   "code": "047810", "suffix": ".KS"},
            {"name": "한화시스템",     "code": "272210", "suffix": ".KS"},
            {"name": "AP위성",         "code": "211270", "suffix": ".KQ"},
            {"name": "쎄트렉아이",     "code": "099550", "suffix": ".KQ"},
            {"name": "컨텍",          "code": "337040", "suffix": ".KQ"},
            {"name": "이노스페이스",   "code": "462350", "suffix": ".KS"},
            {"name": "한화에어로스페이스","code": "012450", "suffix": ".KS"},
        ],
        "함정·레이더": [
            {"name": "한화오션",       "code": "042660", "suffix": ".KS"},
            {"name": "빅텍",          "code": "065450", "suffix": ".KQ"},
            {"name": "스페코",         "code": "013810", "suffix": ".KQ"},
            {"name": "삼강엠앤티",     "code": "100090", "suffix": ".KQ"},
            {"name": "한국신호",       "code": "011400", "suffix": ".KQ"},
        ],
        "탄약·화약": [
            {"name": "풍산",          "code": "103140", "suffix": ".KS"},
            {"name": "한화",          "code": "000880", "suffix": ".KS"},
            {"name": "금양",          "code": "001570", "suffix": ".KS"},
            {"name": "한국화약",       "code": "008420", "suffix": ".KQ"},
        ],
    },
    "조선": {
        "대형 조선소": [
            {"name": "HD한국조선해양", "code": "009540", "suffix": ".KS"},
            {"name": "삼성중공업",     "code": "010140", "suffix": ".KS"},
            {"name": "한화오션",       "code": "042660", "suffix": ".KS"},
            {"name": "HD현대중공업",   "code": "329180", "suffix": ".KS"},
        ],
        "LNG선·특수선": [
            {"name": "HD현대중공업",   "code": "329180", "suffix": ".KS"},
            {"name": "HD현대마린엔진", "code": "082740", "suffix": ".KS"},
            {"name": "STX엔진",        "code": "077970", "suffix": ".KQ"},
            {"name": "현대힘스",       "code": "350520", "suffix": ".KQ"},
        ],
        "기자재·부품": [
            {"name": "동성화인텍",     "code": "033500", "suffix": ".KQ"},
            {"name": "세진중공업",     "code": "075580", "suffix": ".KQ"},
            {"name": "TKG태광",        "code": "023160", "suffix": ".KQ"},
            {"name": "화성밸브",       "code": "038530", "suffix": ".KQ"},
            {"name": "한국카본",       "code": "017960", "suffix": ".KS"},
            {"name": "오리엔탈정공",   "code": "014940", "suffix": ".KS"},
            {"name": "디케이락",       "code": "105740", "suffix": ".KQ"},
            {"name": "현진소재",       "code": "053660", "suffix": ".KQ"},
        ],
        "해운": [
            {"name": "HMM",           "code": "011200", "suffix": ".KS"},
            {"name": "팬오션",         "code": "028670", "suffix": ".KS"},
            {"name": "대한해운",       "code": "005880", "suffix": ".KS"},
            {"name": "흥아해운",       "code": "003280", "suffix": ".KS"},
            {"name": "KSS해운",        "code": "044450", "suffix": ".KQ"},
        ],
    },
    "자동차·전장": {
        "완성차": [
            {"name": "현대차",         "code": "005380", "suffix": ".KS"},
            {"name": "기아",          "code": "000270", "suffix": ".KS"},
            {"name": "쌍용차",         "code": "003620", "suffix": ".KS"},
            {"name": "르노코리아",     "code": "000070", "suffix": ".KS"},
        ],
        "전장·부품": [
            {"name": "현대모비스",     "code": "012330", "suffix": ".KS"},
            {"name": "현대위아",       "code": "011210", "suffix": ".KS"},
            {"name": "한온시스템",     "code": "018880", "suffix": ".KS"},
            {"name": "HL만도",         "code": "204320", "suffix": ".KS"},
            {"name": "성우하이텍",     "code": "015750", "suffix": ".KQ"},
            {"name": "엠에스오토텍",   "code": "123040", "suffix": ".KQ"},
            {"name": "현대트랜시스",   "code": "022250", "suffix": ".KQ"},
            {"name": "에스엘",         "code": "005850", "suffix": ".KS"},
            {"name": "평화산업",       "code": "090080", "suffix": ".KQ"},
        ],
        "타이어": [
            {"name": "한국타이어앤테크놀로지","code": "161390", "suffix": ".KS"},
            {"name": "금호타이어",     "code": "073240", "suffix": ".KS"},
            {"name": "넥센타이어",     "code": "002350", "suffix": ".KS"},
        ],
        "EV 충전·인프라": [
            {"name": "SK시그넷",       "code": "009180", "suffix": ".KQ"},
            {"name": "대영채비",       "code": "084670", "suffix": ".KQ"},
            {"name": "클린일렉스",     "code": "030520", "suffix": ".KQ"},
            {"name": "피에스텍",       "code": "003940", "suffix": ".KQ"},
            {"name": "파워넷",         "code": "037030", "suffix": ".KQ"},
        ],
        "자동차 부품 소재": [
            {"name": "세방전지",       "code": "004490", "suffix": ".KS"},
            {"name": "LS",            "code": "006260", "suffix": ".KS"},
            {"name": "화신",          "code": "010690", "suffix": ".KS"},
            {"name": "대원강업",       "code": "000430", "suffix": ".KS"},
            {"name": "서연이화",       "code": "200880", "suffix": ".KS"},
            {"name": "삼보모터스",     "code": "053700", "suffix": ".KQ"},
        ],
    },
    "원자력": {
        "원전 운영·건설": [
            {"name": "한국전력",       "code": "015760", "suffix": ".KS"},
            {"name": "한전KPS",        "code": "051600", "suffix": ".KS"},
            {"name": "한전기술",       "code": "053590", "suffix": ".KS"},
            {"name": "현대건설",       "code": "000720", "suffix": ".KS"},
            {"name": "삼성물산",       "code": "028260", "suffix": ".KS"},
        ],
        "원전 기자재": [
            {"name": "두산에너빌리티", "code": "034020", "suffix": ".KS"},
            {"name": "비에이치아이",   "code": "083650", "suffix": ".KQ"},
            {"name": "우진",          "code": "105840", "suffix": ".KQ"},
            {"name": "보성파워텍",     "code": "006910", "suffix": ".KQ"},
            {"name": "우리기술",       "code": "032820", "suffix": ".KQ"},
            {"name": "한전산업",       "code": "130660", "suffix": ".KS"},
            {"name": "태웅",          "code": "044490", "suffix": ".KQ"},
            {"name": "서전기전",       "code": "189310", "suffix": ".KQ"},
        ],
        "SMR·차세대원전": [
            {"name": "두산에너빌리티", "code": "034020", "suffix": ".KS"},
            {"name": "현대건설",       "code": "000720", "suffix": ".KS"},
            {"name": "SK이엔에스",     "code": "017900", "suffix": ".KQ"},
            {"name": "지투파워",       "code": "378290", "suffix": ".KQ"},
        ],
        "방사성폐기물·해체": [
            {"name": "한국원자력환경공단","code": "059090", "suffix": ".KQ"},
            {"name": "웰크론한텍",     "code": "076080", "suffix": ".KQ"},
            {"name": "에너토크",       "code": "019770", "suffix": ".KQ"},
            {"name": "삼영엔지니어링", "code": "065370", "suffix": ".KQ"},
        ],
    },
    "전력기기": {
        "변압기": [
            {"name": "효성중공업",     "code": "298040", "suffix": ".KS"},
            {"name": "현대일렉트릭",   "code": "267260", "suffix": ".KS"},
            {"name": "LS ELECTRIC",    "code": "010120", "suffix": ".KS"},
            {"name": "제룡전기",       "code": "033100", "suffix": ".KQ"},
            {"name": "LS",            "code": "006260", "suffix": ".KS"},
            {"name": "일진전기",       "code": "103590", "suffix": ".KS"},
        ],
        "차단기·배전기·케이블": [
            {"name": "일진전기",       "code": "103590", "suffix": ".KS"},
            {"name": "대한전선",       "code": "001440", "suffix": ".KS"},
            {"name": "가온전선",       "code": "000500", "suffix": ".KS"},
            {"name": "광명전기",       "code": "005900", "suffix": ".KQ"},
            {"name": "누리텔레콤",     "code": "040160", "suffix": ".KQ"},
            {"name": "오성첨단소재",   "code": "052420", "suffix": ".KQ"},
            {"name": "LS에코에너지",   "code": "229640", "suffix": ".KQ"},
        ],
        "ESS·에너지저장": [
            {"name": "비나텍",         "code": "002070", "suffix": ".KQ"},
            {"name": "에너테크인터내셔널","code": "016250", "suffix": ".KQ"},
            {"name": "두산퓨얼셀",     "code": "336260", "suffix": ".KQ"},
            {"name": "OCI홀딩스",      "code": "010060", "suffix": ".KS"},
        ],
        "스마트그리드·전력솔루션": [
            {"name": "우리기술투자",   "code": "041190", "suffix": ".KQ"},
            {"name": "비츠로시스",     "code": "054220", "suffix": ".KQ"},
            {"name": "옴니시스템",     "code": "057540", "suffix": ".KQ"},
        ],
        "태양광·풍력": [
            {"name": "한화솔루션",     "code": "009830", "suffix": ".KS"},
            {"name": "OCI홀딩스",      "code": "010060", "suffix": ".KS"},
            {"name": "씨에스윈드",     "code": "112610", "suffix": ".KS"},
            {"name": "유니슨",         "code": "018000", "suffix": ".KQ"},
            {"name": "동국S&C",        "code": "100130", "suffix": ".KQ"},
            {"name": "신성이엔지",     "code": "011930", "suffix": ".KQ"},
        ],
    },
    "게임·엔터": {
        "PC·콘솔 게임": [
            {"name": "크래프톤",       "code": "259960", "suffix": ".KS"},
            {"name": "넥슨게임즈",     "code": "225130", "suffix": ".KQ"},
            {"name": "엔씨소프트",     "code": "036570", "suffix": ".KS"},
            {"name": "넷마블",         "code": "251270", "suffix": ".KS"},
            {"name": "시프트업",       "code": "462870", "suffix": ".KS"},
            {"name": "펄어비스",       "code": "263750", "suffix": ".KQ"},
        ],
        "모바일 게임": [
            {"name": "컴투스",         "code": "078340", "suffix": ".KQ"},
            {"name": "카카오게임즈",   "code": "293490", "suffix": ".KQ"},
            {"name": "위메이드",       "code": "112040", "suffix": ".KQ"},
            {"name": "데브시스터즈",   "code": "194480", "suffix": ".KQ"},
            {"name": "네오위즈",       "code": "095660", "suffix": ".KQ"},
            {"name": "컴투스홀딩스",   "code": "063080", "suffix": ".KQ"},
            {"name": "선데이토즈",     "code": "123420", "suffix": ".KQ"},
        ],
        "K-팝·엔터테인먼트": [
            {"name": "HYBE",          "code": "352820", "suffix": ".KS"},
            {"name": "SM엔터테인먼트", "code": "041510", "suffix": ".KQ"},
            {"name": "JYP Ent.",       "code": "035900", "suffix": ".KQ"},
            {"name": "YG엔터테인먼트", "code": "122870", "suffix": ".KQ"},
            {"name": "FNC엔터테인먼트", "code": "173940", "suffix": ".KQ"},
            {"name": "큐브엔터",       "code": "182360", "suffix": ".KQ"},
        ],
        "OTT·콘텐츠·미디어": [
            {"name": "CJ ENM",         "code": "035760", "suffix": ".KQ"},
            {"name": "스튜디오드래곤", "code": "253450", "suffix": ".KQ"},
            {"name": "콘텐트리중앙",   "code": "036420", "suffix": ".KS"},
            {"name": "초록뱀미디어",   "code": "047820", "suffix": ".KQ"},
            {"name": "에이스토리",     "code": "241840", "suffix": ".KQ"},
            {"name": "NHN",           "code": "181710", "suffix": ".KS"},
        ],
        "웹툰·IP": [
            {"name": "NAVER",         "code": "035420", "suffix": ".KS"},
            {"name": "카카오",         "code": "035720", "suffix": ".KS"},
            {"name": "디앤씨미디어",   "code": "263020", "suffix": ".KQ"},
            {"name": "투바이츠",       "code": "199800", "suffix": ".KQ"},
        ],
    },
    "뷰티·K-뷰티": {
        "화장품 대기업": [
            {"name": "아모레퍼시픽",   "code": "090430", "suffix": ".KS"},
            {"name": "LG생활건강",     "code": "051900", "suffix": ".KS"},
            {"name": "애경산업",       "code": "018250", "suffix": ".KS"},
            {"name": "토니모리",       "code": "214420", "suffix": ".KQ"},
        ],
        "인디·ODM": [
            {"name": "코스맥스",       "code": "192820", "suffix": ".KS"},
            {"name": "한국콜마",       "code": "161890", "suffix": ".KS"},
            {"name": "코스메카코리아", "code": "241710", "suffix": ".KQ"},
            {"name": "씨앤씨인터내셔널","code": "352480", "suffix": ".KQ"},
            {"name": "코스온",         "code": "069110", "suffix": ".KQ"},
            {"name": "아우딘퓨쳐스",   "code": "227550", "suffix": ".KQ"},
        ],
        "기능성·이너뷰티": [
            {"name": "클리오",         "code": "237880", "suffix": ".KQ"},
            {"name": "에이피알",       "code": "032120", "suffix": ".KQ"},
            {"name": "브이티",         "code": "018990", "suffix": ".KQ"},
            {"name": "마녀공장",       "code": "439090", "suffix": ".KQ"},
            {"name": "실리콘투",       "code": "257720", "suffix": ".KQ"},
            {"name": "아이패밀리에스씨","code": "114840", "suffix": ".KQ"},
        ],
        "면세·유통": [
            {"name": "호텔신라",       "code": "008770", "suffix": ".KS"},
            {"name": "현대백화점",     "code": "069960", "suffix": ".KS"},
            {"name": "신세계",         "code": "004170", "suffix": ".KS"},
            {"name": "롯데쇼핑",       "code": "023530", "suffix": ".KS"},
            {"name": "신세계인터내셔날","code": "031430", "suffix": ".KS"},
        ],
    },
    "금융·은행": {
        "은행·지주": [
            {"name": "KB금융",         "code": "105560", "suffix": ".KS"},
            {"name": "신한지주",       "code": "055550", "suffix": ".KS"},
            {"name": "하나금융지주",   "code": "086790", "suffix": ".KS"},
            {"name": "우리금융지주",   "code": "316140", "suffix": ".KS"},
            {"name": "기업은행",       "code": "024110", "suffix": ".KS"},
            {"name": "BNK금융지주",    "code": "138930", "suffix": ".KS"},
            {"name": "DGB금융지주",    "code": "139130", "suffix": ".KS"},
            {"name": "JB금융지주",     "code": "175330", "suffix": ".KS"},
        ],
        "보험": [
            {"name": "삼성생명",       "code": "032830", "suffix": ".KS"},
            {"name": "삼성화재",       "code": "000810", "suffix": ".KS"},
            {"name": "한화생명",       "code": "088350", "suffix": ".KS"},
            {"name": "현대해상",       "code": "001450", "suffix": ".KS"},
            {"name": "DB손해보험",     "code": "005830", "suffix": ".KS"},
            {"name": "메리츠화재",     "code": "000060", "suffix": ".KS"},
            {"name": "미래에셋생명",   "code": "085620", "suffix": ".KS"},
        ],
        "증권": [
            {"name": "미래에셋증권",   "code": "006800", "suffix": ".KS"},
            {"name": "키움증권",       "code": "039490", "suffix": ".KQ"},
            {"name": "한국금융지주",   "code": "071050", "suffix": ".KS"},
            {"name": "NH투자증권",     "code": "005940", "suffix": ".KS"},
            {"name": "삼성증권",       "code": "016360", "suffix": ".KS"},
            {"name": "메리츠증권",     "code": "008560", "suffix": ".KS"},
            {"name": "대신증권",       "code": "003540", "suffix": ".KS"},
        ],
        "카드·캐피탈": [
            {"name": "삼성카드",       "code": "029780", "suffix": ".KS"},
            {"name": "롯데지주",       "code": "004990", "suffix": ".KS"},
        ],
        "핀테크": [
            {"name": "카카오뱅크",     "code": "323410", "suffix": ".KS"},
            {"name": "카카오페이",     "code": "377300", "suffix": ".KS"},
            {"name": "한국정보통신",   "code": "025770", "suffix": ".KQ"},
            {"name": "나이스정보통신", "code": "036800", "suffix": ".KQ"},
            {"name": "웹케시",         "code": "053580", "suffix": ".KQ"},
            {"name": "NHN(페이코)",    "code": "181710", "suffix": ".KS"},
        ],
    },
    "화학·소재": {
        "석유화학": [
            {"name": "LG화학",         "code": "051910", "suffix": ".KS"},
            {"name": "롯데케미칼",     "code": "011170", "suffix": ".KS"},
            {"name": "한화솔루션",     "code": "009830", "suffix": ".KS"},
            {"name": "금호석유",       "code": "011780", "suffix": ".KS"},
            {"name": "SK이노베이션",   "code": "096770", "suffix": ".KS"},
            {"name": "효성화학",       "code": "298000", "suffix": ".KS"},
        ],
        "정밀화학·특수소재": [
            {"name": "효성첨단소재",   "code": "298050", "suffix": ".KS"},
            {"name": "SKC",            "code": "011790", "suffix": ".KS"},
            {"name": "코오롱인더",     "code": "120110", "suffix": ".KS"},
            {"name": "OCI홀딩스",      "code": "010060", "suffix": ".KS"},
            {"name": "케이씨씨",       "code": "002380", "suffix": ".KS"},
            {"name": "KCC글라스",      "code": "344820", "suffix": ".KS"},
            {"name": "하나머티리얼즈", "code": "166090", "suffix": ".KQ"},
        ],
        "철강·금속": [
            {"name": "POSCO홀딩스",    "code": "005490", "suffix": ".KS"},
            {"name": "현대제철",       "code": "004020", "suffix": ".KS"},
            {"name": "고려아연",       "code": "010130", "suffix": ".KS"},
            {"name": "풍산",          "code": "103140", "suffix": ".KS"},
            {"name": "세아베스틸지주", "code": "001430", "suffix": ".KS"},
            {"name": "동국제강",       "code": "001230", "suffix": ".KS"},
            {"name": "포스코인터내셔널","code": "047050", "suffix": ".KS"},
        ],
        "기능성 필름·디스플레이 소재": [
            {"name": "동우화인켐",     "code": "008000", "suffix": ".KS"},
            {"name": "이녹스첨단소재", "code": "272290", "suffix": ".KQ"},
            {"name": "LX하우시스",     "code": "108670", "suffix": ".KS"},
            {"name": "켐트로닉스",     "code": "089010", "suffix": ".KQ"},
            {"name": "미래나노텍",     "code": "095500", "suffix": ".KQ"},
        ],
    },
    "건설·인프라": {
        "대형 건설": [
            {"name": "삼성물산",       "code": "028260", "suffix": ".KS"},
            {"name": "현대건설",       "code": "000720", "suffix": ".KS"},
            {"name": "GS건설",         "code": "006360", "suffix": ".KS"},
            {"name": "DL이앤씨",       "code": "375500", "suffix": ".KS"},
            {"name": "SK에코플랜트",   "code": "034730", "suffix": ".KS"},
        ],
        "주택·부동산": [
            {"name": "HDC현대산업개발","code": "294870", "suffix": ".KS"},
            {"name": "대우건설",       "code": "047040", "suffix": ".KS"},
            {"name": "태영건설",       "code": "009410", "suffix": ".KS"},
            {"name": "두산건설",       "code": "011160", "suffix": ".KS"},
            {"name": "금호건설",       "code": "002990", "suffix": ".KS"},
        ],
        "인프라·시멘트": [
            {"name": "한국전력",       "code": "015760", "suffix": ".KS"},
            {"name": "쌍용C&E",        "code": "003410", "suffix": ".KS"},
            {"name": "아세아시멘트",   "code": "183190", "suffix": ".KS"},
            {"name": "성신양회",       "code": "004980", "suffix": ".KQ"},
            {"name": "한일시멘트",     "code": "003300", "suffix": ".KS"},
            {"name": "삼표시멘트",     "code": "038500", "suffix": ".KQ"},
        ],
        "엔지니어링·플랜트": [
            {"name": "한미글로벌",     "code": "053690", "suffix": ".KQ"},
            {"name": "계룡건설",       "code": "013580", "suffix": ".KS"},
            {"name": "삼부토건",       "code": "001470", "suffix": ".KS"},
            {"name": "한국종합기술",   "code": "225570", "suffix": ".KQ"},
        ],
    },
    "통신": {
        "이동통신": [
            {"name": "SK텔레콤",       "code": "017670", "suffix": ".KS"},
            {"name": "KT",            "code": "030200", "suffix": ".KS"},
            {"name": "LG유플러스",     "code": "032640", "suffix": ".KS"},
        ],
        "미디어·플랫폼": [
            {"name": "카카오",         "code": "035720", "suffix": ".KS"},
            {"name": "NAVER",         "code": "035420", "suffix": ".KS"},
            {"name": "NHN",           "code": "181710", "suffix": ".KS"},
            {"name": "드림어스컴퍼니", "code": "115180", "suffix": ".KQ"},
            {"name": "KT알파",         "code": "035540", "suffix": ".KQ"},
        ],
        "유통·이커머스": [
            {"name": "롯데쇼핑",       "code": "023530", "suffix": ".KS"},
            {"name": "이마트",         "code": "139480", "suffix": ".KS"},
            {"name": "GS리테일",       "code": "007070", "suffix": ".KS"},
            {"name": "BGF리테일",      "code": "027410", "suffix": ".KS"},
            {"name": "현대홈쇼핑",     "code": "057050", "suffix": ".KS"},
            {"name": "GS홈쇼핑",       "code": "028150", "suffix": ".KQ"},
        ],
        "네트워크·통신장비": [
            {"name": "RFHIC",         "code": "218410", "suffix": ".KQ"},
            {"name": "이노와이어리스", "code": "073490", "suffix": ".KQ"},
            {"name": "쏠리드",         "code": "050890", "suffix": ".KQ"},
            {"name": "에치에프알",     "code": "230240", "suffix": ".KQ"},
            {"name": "유비쿼스홀딩스", "code": "078070", "suffix": ".KQ"},
        ],
    },
    "수소·친환경에너지": {
        "수소 생산·저장": [
            {"name": "두산퓨얼셀",     "code": "336260", "suffix": ".KQ"},
            {"name": "일진하이솔루스", "code": "271940", "suffix": ".KQ"},
            {"name": "효성중공업",     "code": "298040", "suffix": ".KS"},
            {"name": "코오롱인더",     "code": "120110", "suffix": ".KS"},
            {"name": "제이엔케이히터", "code": "126880", "suffix": ".KQ"},
        ],
        "연료전지": [
            {"name": "두산퓨얼셀",     "code": "336260", "suffix": ".KQ"},
            {"name": "에스퓨얼셀",     "code": "288620", "suffix": ".KQ"},
            {"name": "범한퓨얼셀",     "code": "382900", "suffix": ".KQ"},
        ],
        "배터리 재활용·희소금속": [
            {"name": "에코프로",       "code": "086520", "suffix": ".KQ"},
            {"name": "새빗켐",         "code": "452860", "suffix": ".KQ"},
            {"name": "성일하이텍",     "code": "024840", "suffix": ".KQ"},
            {"name": "고려아연",       "code": "010130", "suffix": ".KS"},
            {"name": "포스코홀딩스",   "code": "005490", "suffix": ".KS"},
        ],
    },
    "물류·여행": {
        "물류·택배": [
            {"name": "CJ대한통운",     "code": "000120", "suffix": ".KS"},
            {"name": "한진",          "code": "002320", "suffix": ".KS"},
            {"name": "케이씨티씨",     "code": "009280", "suffix": ".KS"},
            {"name": "현대글로비스",   "code": "086280", "suffix": ".KS"},
        ],
        "항공·여행": [
            {"name": "대한항공",       "code": "003490", "suffix": ".KS"},
            {"name": "아시아나항공",   "code": "020560", "suffix": ".KS"},
            {"name": "제주항공",       "code": "089590", "suffix": ".KQ"},
            {"name": "진에어",         "code": "272450", "suffix": ".KS"},
            {"name": "티웨이항공",     "code": "091810", "suffix": ".KQ"},
            {"name": "에어부산",       "code": "298690", "suffix": ".KQ"},
            {"name": "하나투어",       "code": "039130", "suffix": ".KQ"},
            {"name": "모두투어",       "code": "080160", "suffix": ".KQ"},
        ],
    },
    "식품·소비재": {
        "가공식품·음료": [
            {"name": "CJ제일제당",     "code": "097950", "suffix": ".KS"},
            {"name": "오리온",         "code": "271560", "suffix": ".KS"},
            {"name": "농심",          "code": "004370", "suffix": ".KS"},
            {"name": "빙그레",         "code": "005180", "suffix": ".KS"},
            {"name": "삼양식품",       "code": "003230", "suffix": ".KS"},
            {"name": "오뚜기",         "code": "007310", "suffix": ".KS"},
            {"name": "동원F&B",        "code": "049770", "suffix": ".KS"},
            {"name": "롯데웰푸드",     "code": "280360", "suffix": ".KS"},
        ],
        "주류·음료": [
            {"name": "하이트진로",     "code": "000080", "suffix": ".KS"},
            {"name": "롯데칠성음료",   "code": "005300", "suffix": ".KS"},
            {"name": "KT&G",           "code": "033780", "suffix": ".KS"},
            {"name": "무학",          "code": "033920", "suffix": ".KQ"},
        ],
        "생활용품·위생": [
            {"name": "깨끗한나라",     "code": "004540", "suffix": ".KQ"},
            {"name": "크린앤사이언스", "code": "045520", "suffix": ".KQ"},
            {"name": "쌍용씨앤비",     "code": "012650", "suffix": ".KQ"},
        ],
        "외식·프랜차이즈": [
            {"name": "교촌에프앤비",   "code": "339770", "suffix": ".KQ"},
            {"name": "더본코리아",     "code": "475000", "suffix": ".KQ"},
            {"name": "CJ CGV",        "code": "079160", "suffix": ".KS"},
        ],
    },
    "양자컴퓨터·암호": {
        "양자 보안·암호화": [
            {"name": "SK텔레콤",       "code": "017670", "suffix": ".KS"},
            {"name": "ICTK홀딩스",     "code": "040850", "suffix": ".KQ"},
            {"name": "우리로",         "code": "043590", "suffix": ".KQ"},
            {"name": "드림시큐리티",   "code": "203650", "suffix": ".KQ"},
            {"name": "라온시큐어",     "code": "042510", "suffix": ".KQ"},
            {"name": "이니텍",         "code": "053350", "suffix": ".KQ"},
        ],
        "양자 컴퓨팅·소재": [
            {"name": "삼성전자",       "code": "005930", "suffix": ".KS"},
            {"name": "SK하이닉스",     "code": "000660", "suffix": ".KS"},
            {"name": "LG전자",         "code": "066570", "suffix": ".KS"},
            {"name": "에스앤에스텍",   "code": "101490", "suffix": ".KQ"},
        ],
        "포스트퀀텀·사이버보안": [
            {"name": "안랩",           "code": "053800", "suffix": ".KQ"},
            {"name": "이스트소프트",   "code": "047560", "suffix": ".KQ"},
            {"name": "파수",           "code": "150900", "suffix": ".KQ"},
            {"name": "윈스",           "code": "136540", "suffix": ".KQ"},
            {"name": "지니언스",       "code": "263860", "suffix": ".KQ"},
        ],
    },
    "우주·항공우주": {
        "발사체·위성 제조": [
            {"name": "한국항공우주",   "code": "047810", "suffix": ".KS"},
            {"name": "이노스페이스",   "code": "462350", "suffix": ".KS"},
            {"name": "쎄트렉아이",     "code": "099550", "suffix": ".KQ"},
            {"name": "AP위성",         "code": "211270", "suffix": ".KQ"},
            {"name": "컨텍",          "code": "337040", "suffix": ".KQ"},
            {"name": "한화에어로스페이스","code": "012450", "suffix": ".KS"},
        ],
        "항공 부품·MRO": [
            {"name": "한국항공우주",   "code": "047810", "suffix": ".KS"},
            {"name": "켄코아에어로스페이스","code": "274090", "suffix": ".KQ"},
            {"name": "아스트",         "code": "067390", "suffix": ".KQ"},
            {"name": "한국항공서비스(대한항공)","code": "003490", "suffix": ".KS"},
            {"name": "시이오더블유",   "code": "082660", "suffix": ".KQ"},
        ],
        "위성 통신·항법": [
            {"name": "AP위성",         "code": "211270", "suffix": ".KQ"},
            {"name": "쎄트렉아이",     "code": "099550", "suffix": ".KQ"},
            {"name": "SK텔레콤",       "code": "017670", "suffix": ".KS"},
            {"name": "KT",            "code": "030200", "suffix": ".KS"},
            {"name": "인텔리안테크",   "code": "189300", "suffix": ".KQ"},
        ],
    },
    "메타버스·XR": {
        "VR·AR 기기": [
            {"name": "LG전자",         "code": "066570", "suffix": ".KS"},
            {"name": "삼성전자",       "code": "005930", "suffix": ".KS"},
            {"name": "하이비전시스템", "code": "126700", "suffix": ".KQ"},
            {"name": "맥스트",         "code": "377030", "suffix": ".KQ"},
            {"name": "버넥트",         "code": "438700", "suffix": ".KQ"},
        ],
        "메타버스 콘텐츠·플랫폼": [
            {"name": "NAVER",         "code": "035420", "suffix": ".KS"},
            {"name": "카카오",         "code": "035720", "suffix": ".KS"},
            {"name": "컴투스",         "code": "078340", "suffix": ".KQ"},
            {"name": "위메이드",       "code": "112040", "suffix": ".KQ"},
            {"name": "위지윅스튜디오", "code": "299900", "suffix": ".KQ"},
            {"name": "자이언트스텝",   "code": "289220", "suffix": ".KQ"},
        ],
        "블록체인·NFT": [
            {"name": "위메이드",       "code": "112040", "suffix": ".KQ"},
            {"name": "카카오",         "code": "035720", "suffix": ".KS"},
            {"name": "갤럭시아머니트리","code": "094480", "suffix": ".KQ"},
            {"name": "서울옥션",       "code": "063170", "suffix": ".KQ"},
        ],
    },

    # ── 신규 섹터 (2025 확장) ────────────────────────────────────────────────

    "조선·해운": {
        "대형조선": [
            {"name": "HD한국조선해양", "code": "009540", "suffix": ".KS"},
            {"name": "삼성중공업",     "code": "010140", "suffix": ".KS"},
            {"name": "한화오션",       "code": "042660", "suffix": ".KS"},
            {"name": "HD현대중공업",   "code": "329180", "suffix": ".KS"},
            {"name": "HD현대미포",     "code": "010620", "suffix": ".KS"},
            {"name": "HD현대",         "code": "267250", "suffix": ".KS"},
            {"name": "STX엔진",        "code": "077970", "suffix": ".KS"},
            {"name": "한화엔진",       "code": "082740", "suffix": ".KS"},
        ],
        "조선 기자재·부품": [
            {"name": "세진중공업",     "code": "075580", "suffix": ".KQ"},
            {"name": "한국카본",       "code": "017960", "suffix": ".KS"},
            {"name": "동성화인텍",     "code": "033500", "suffix": ".KQ"},
            {"name": "케이조선",       "code": "023160", "suffix": ".KQ"},
            {"name": "성광벤드",       "code": "014620", "suffix": ".KS"},
            {"name": "한라IMS",        "code": "092460", "suffix": ".KQ"},
            {"name": "대창솔루션",     "code": "096350", "suffix": ".KQ"},
            {"name": "태광",           "code": "023160", "suffix": ".KQ"},
        ],
        "해운·항만": [
            {"name": "HMM",           "code": "011200", "suffix": ".KS"},
            {"name": "팬오션",         "code": "028670", "suffix": ".KS"},
            {"name": "KSS해운",        "code": "044450", "suffix": ".KS"},
            {"name": "대한해운",       "code": "005880", "suffix": ".KS"},
            {"name": "흥아해운",       "code": "003280", "suffix": ".KS"},
            {"name": "CJ대한통운",     "code": "000120", "suffix": ".KS"},
            {"name": "현대글로비스",   "code": "086280", "suffix": ".KS"},
            {"name": "한진",           "code": "002320", "suffix": ".KS"},
            {"name": "동방",           "code": "004140", "suffix": ".KS"},
        ],
    },

    "방위산업": {
        "지상무기·탄약": [
            {"name": "한화에어로스페이스","code": "012450", "suffix": ".KS"},
            {"name": "현대로템",       "code": "064350", "suffix": ".KS"},
            {"name": "풍산",           "code": "103140", "suffix": ".KS"},
            {"name": "한화",           "code": "000880", "suffix": ".KS"},
            {"name": "S&T중공업",      "code": "003570", "suffix": ".KS"},
            {"name": "SNT모티브",      "code": "064960", "suffix": ".KS"},
            {"name": "퍼스텍",         "code": "010820", "suffix": ".KS"},
            {"name": "S&T홀딩스",      "code": "100840", "suffix": ".KS"},
        ],
        "항공·함정무기": [
            {"name": "한국항공우주",   "code": "047810", "suffix": ".KS"},
            {"name": "LIG넥스원",      "code": "079550", "suffix": ".KS"},
            {"name": "한화시스템",     "code": "272210", "suffix": ".KS"},
            {"name": "쎄트렉아이",     "code": "099550", "suffix": ".KQ"},
            {"name": "빅텍",           "code": "065450", "suffix": ".KQ"},
            {"name": "한화오션",       "code": "042660", "suffix": ".KS"},
            {"name": "현대중공업",     "code": "329180", "suffix": ".KS"},
        ],
        "방산전자·드론": [
            {"name": "한화시스템",     "code": "272210", "suffix": ".KS"},
            {"name": "LIG넥스원",      "code": "079550", "suffix": ".KS"},
            {"name": "아이쓰리시스템", "code": "214430", "suffix": ".KQ"},
            {"name": "한국항공우주",   "code": "047810", "suffix": ".KS"},
            {"name": "유콘시스템",     "code": "023350", "suffix": ".KQ"},
            {"name": "우리기술",       "code": "032820", "suffix": ".KQ"},
            {"name": "휴니드",         "code": "005010", "suffix": ".KS"},
            {"name": "스페코",         "code": "013810", "suffix": ".KQ"},
        ],
    },

    "건설·부동산": {
        "대형건설": [
            {"name": "삼성물산",       "code": "028260", "suffix": ".KS"},
            {"name": "현대건설",       "code": "000720", "suffix": ".KS"},
            {"name": "대우건설",       "code": "047040", "suffix": ".KS"},
            {"name": "GS건설",         "code": "006360", "suffix": ".KS"},
            {"name": "DL이앤씨",       "code": "375500", "suffix": ".KS"},
            {"name": "포스코이앤씨",   "code": "047050", "suffix": ".KS"},
            {"name": "HDC현대산업개발","code": "294870", "suffix": ".KS"},
            {"name": "삼성엔지니어링", "code": "028050", "suffix": ".KS"},
        ],
        "중소건설·주택": [
            {"name": "계룡건설산업",   "code": "013580", "suffix": ".KS"},
            {"name": "태영건설",       "code": "009410", "suffix": ".KS"},
            {"name": "코오롱글로벌",   "code": "003070", "suffix": ".KS"},
            {"name": "신세계건설",     "code": "034300", "suffix": ".KS"},
            {"name": "서한",           "code": "018680", "suffix": ".KQ"},
            {"name": "두산에너빌리티", "code": "034020", "suffix": ".KS"},
            {"name": "HJ중공업",       "code": "097230", "suffix": ".KS"},
        ],
        "리츠·부동산": [
            {"name": "맥쿼리인프라",   "code": "088980", "suffix": ".KS"},
            {"name": "ESR켄달스퀘어리츠","code": "365550", "suffix": ".KS"},
            {"name": "신한알파리츠",   "code": "293940", "suffix": ".KS"},
            {"name": "한국토지신탁",   "code": "034830", "suffix": ".KS"},
            {"name": "이지스레지던스리츠","code": "350520", "suffix": ".KS"},
            {"name": "케이탑리츠",     "code": "337150", "suffix": ".KS"},
            {"name": "코람코에너지리츠","code": "434490", "suffix": ".KS"},
        ],
    },

    "은행·금융지주": {
        "4대금융지주": [
            {"name": "KB금융",         "code": "105560", "suffix": ".KS"},
            {"name": "신한지주",       "code": "055550", "suffix": ".KS"},
            {"name": "하나금융지주",   "code": "086790", "suffix": ".KS"},
            {"name": "우리금융지주",   "code": "316140", "suffix": ".KS"},
            {"name": "BNK금융지주",    "code": "138930", "suffix": ".KS"},
            {"name": "DGB금융지주",    "code": "139130", "suffix": ".KS"},
            {"name": "JB금융지주",     "code": "175330", "suffix": ".KS"},
        ],
        "인터넷은행·핀테크": [
            {"name": "카카오뱅크",     "code": "323410", "suffix": ".KS"},
            {"name": "카카오페이",     "code": "377300", "suffix": ".KS"},
            {"name": "NHN KCP",        "code": "060250", "suffix": ".KQ"},
            {"name": "한국금융지주",   "code": "071050", "suffix": ".KS"},
            {"name": "웰컴저축은행",   "code": "046310", "suffix": ".KQ"},
        ],
        "카드·캐피탈": [
            {"name": "메리츠금융지주", "code": "138040", "suffix": ".KS"},
            {"name": "한국캐피탈",     "code": "024110", "suffix": ".KQ"},
        ],
    },

    "보험·증권": {
        "생명보험": [
            {"name": "삼성생명",       "code": "032830", "suffix": ".KS"},
            {"name": "한화생명",       "code": "088350", "suffix": ".KS"},
            {"name": "미래에셋생명",   "code": "085620", "suffix": ".KS"},
            {"name": "동양생명",       "code": "082640", "suffix": ".KS"},
        ],
        "손해보험": [
            {"name": "삼성화재",       "code": "000810", "suffix": ".KS"},
            {"name": "DB손해보험",     "code": "005830", "suffix": ".KS"},
            {"name": "현대해상",       "code": "001450", "suffix": ".KS"},
            {"name": "메리츠화재",     "code": "000060", "suffix": ".KS"},
            {"name": "한화손해보험",   "code": "000370", "suffix": ".KS"},
        ],
        "대형증권": [
            {"name": "미래에셋증권",   "code": "006800", "suffix": ".KS"},
            {"name": "NH투자증권",     "code": "005940", "suffix": ".KS"},
            {"name": "삼성증권",       "code": "016360", "suffix": ".KS"},
            {"name": "키움증권",       "code": "039490", "suffix": ".KQ"},
            {"name": "한화투자증권",   "code": "003530", "suffix": ".KS"},
            {"name": "유안타증권",     "code": "003470", "suffix": ".KS"},
            {"name": "대신증권",       "code": "003540", "suffix": ".KS"},
        ],
    },

    "철강·금속·광물": {
        "철강": [
            {"name": "POSCO홀딩스",    "code": "005490", "suffix": ".KS"},
            {"name": "현대제철",       "code": "004020", "suffix": ".KS"},
            {"name": "동국제강",       "code": "460860", "suffix": ".KS"},
            {"name": "세아베스틸지주", "code": "001430", "suffix": ".KS"},
            {"name": "포스코스틸리온", "code": "058430", "suffix": ".KS"},
            {"name": "동국씨엠",       "code": "025890", "suffix": ".KS"},
            {"name": "KG스틸",         "code": "016380", "suffix": ".KS"},
        ],
        "비철금속·희소금속": [
            {"name": "고려아연",       "code": "010130", "suffix": ".KS"},
            {"name": "풍산",           "code": "103140", "suffix": ".KS"},
            {"name": "영풍",           "code": "000670", "suffix": ".KS"},
            {"name": "황금에스티",     "code": "032560", "suffix": ".KQ"},
            {"name": "알루코",         "code": "001780", "suffix": ".KS"},
            {"name": "대창",           "code": "015590", "suffix": ".KS"},
            {"name": "이구산업",       "code": "025820", "suffix": ".KS"},
        ],
        "광물·자원개발": [
            {"name": "포스코인터내셔널","code": "047050", "suffix": ".KS"},
            {"name": "SK이노베이션",   "code": "096770", "suffix": ".KS"},
            {"name": "한국가스공사",   "code": "036460", "suffix": ".KS"},
            {"name": "한국전력",       "code": "015760", "suffix": ".KS"},
            {"name": "삼탄",           "code": "000650", "suffix": ".KS"},
        ],
    },

    "유통·소매": {
        "대형유통·백화점": [
            {"name": "롯데쇼핑",       "code": "023530", "suffix": ".KS"},
            {"name": "신세계",         "code": "004170", "suffix": ".KS"},
            {"name": "현대백화점",     "code": "069960", "suffix": ".KS"},
            {"name": "이마트",         "code": "139480", "suffix": ".KS"},
            {"name": "롯데하이마트",   "code": "071840", "suffix": ".KS"},
        ],
        "편의점·슈퍼": [
            {"name": "BGF리테일",      "code": "282330", "suffix": ".KS"},
            {"name": "GS리테일",       "code": "007070", "suffix": ".KS"},
        ],
        "이커머스·배달": [
            {"name": "카카오",         "code": "035720", "suffix": ".KS"},
            {"name": "NAVER",         "code": "035420", "suffix": ".KS"},
            {"name": "오아시스",       "code": "101360", "suffix": ".KQ"},
        ],
        "홈쇼핑·TV커머스": [
            {"name": "CJ온스타일",     "code": "035760", "suffix": ".KS"},
            {"name": "GS홈쇼핑",       "code": "028150", "suffix": ".KS"},
            {"name": "현대홈쇼핑",     "code": "057050", "suffix": ".KS"},
            {"name": "NS홈쇼핑",       "code": "057060", "suffix": ".KS"},
        ],
    },

    "미디어·광고·콘텐츠": {
        "방송·OTT": [
            {"name": "CJ ENM",         "code": "035760", "suffix": ".KS"},
            {"name": "SBS",            "code": "034120", "suffix": ".KS"},
            {"name": "스튜디오드래곤", "code": "253450", "suffix": ".KQ"},
            {"name": "NEW",            "code": "160550", "suffix": ".KQ"},
            {"name": "에이스토리",     "code": "241840", "suffix": ".KQ"},
        ],
        "광고·마케팅": [
            {"name": "제일기획",       "code": "030000", "suffix": ".KS"},
            {"name": "이노션",         "code": "214320", "suffix": ".KS"},
            {"name": "오리콤",         "code": "010470", "suffix": ".KS"},
            {"name": "나스미디어",     "code": "089600", "suffix": ".KQ"},
            {"name": "인크로스",       "code": "216050", "suffix": ".KQ"},
            {"name": "모비데이즈",     "code": "363280", "suffix": ".KQ"},
        ],
        "출판·교육콘텐츠": [
            {"name": "웅진씽크빅",     "code": "095720", "suffix": ".KQ"},
            {"name": "메가스터디",     "code": "072870", "suffix": ".KQ"},
            {"name": "대교",           "code": "019680", "suffix": ".KS"},
            {"name": "NE능률",         "code": "053300", "suffix": ".KQ"},
        ],
    },

    "교육·이러닝": {
        "이러닝·에듀테크": [
            {"name": "메가스터디교육", "code": "215200", "suffix": ".KQ"},
            {"name": "비상교육",       "code": "100220", "suffix": ".KQ"},
        ],
        "어학·자격증": [
        ],
        "유아·초중고교육": [
            {"name": "웅진씽크빅",     "code": "095720", "suffix": ".KQ"},
            {"name": "대교",           "code": "019680", "suffix": ".KS"},
            {"name": "청담러닝",       "code": "051380", "suffix": ".KQ"},
            {"name": "아이스크림에듀", "code": "289010", "suffix": ".KQ"},
        ],
    },

    "광통신·네트워크장비": {
        "광통신 부품·모듈": [
            {"name": "오이솔루션",     "code": "138080", "suffix": ".KQ"},
            {"name": "우리로",         "code": "043590", "suffix": ".KQ"},
            {"name": "옵티시스",       "code": "109080", "suffix": ".KQ"},
            {"name": "이노와이어리스", "code": "073490", "suffix": ".KQ"},
            {"name": "에치에프알",     "code": "230340", "suffix": ".KQ"},
            {"name": "코위버",         "code": "056360", "suffix": ".KQ"},
            {"name": "파이버프로",     "code": "100700", "suffix": ".KQ"},
            {"name": "빛과전자",       "code": "082660", "suffix": ".KQ"},
        ],
        "네트워크 장비": [
            {"name": "다산네트웍스",   "code": "039560", "suffix": ".KQ"},
            {"name": "유비쿼스",       "code": "078070", "suffix": ".KQ"},
            {"name": "쏠리드",         "code": "050890", "suffix": ".KQ"},
            {"name": "엑스플라",       "code": "088800", "suffix": ".KQ"},
            {"name": "에이치엘비파워", "code": "043220", "suffix": ".KQ"},
            {"name": "케이엠더블유",   "code": "032500", "suffix": ".KQ"},
            {"name": "서진시스템",     "code": "178320", "suffix": ".KQ"},
        ],
        "IDC·클라우드인프라": [
            {"name": "KT",            "code": "030200", "suffix": ".KS"},
            {"name": "SK텔레콤",       "code": "017670", "suffix": ".KS"},
            {"name": "LG유플러스",     "code": "032640", "suffix": ".KS"},
            {"name": "삼성SDS",        "code": "018260", "suffix": ".KS"},
            {"name": "가비아",         "code": "079940", "suffix": ".KQ"},
        ],
    },
}
