# 미국 주식 티커 - 한국어 종목명 매핑 데이터베이스
# 주요 1,000개 이상의 종목 및 ETF 포함

US_KR_NAME_MAP = {
    "AAPL": "애플",
    "MSFT": "마이크로소프트",
    "NVDA": "엔비디아",
    "AMZN": "아마존",
    "GOOGL": "알파벳(구글)",
    "GOOG": "알파벳(구글)",
    "META": "메타",
    "TSLA": "테슬라",
    "BRK-B": "버크셔해서웨이",
    "LLY": "일라이릴리",
    "AVGO": "브로드컴",
    "V": "비자",
    "JPM": "JP모건",
    "TSM": "TSMC",
    "WMT": "월마트",
    "MA": "마스터카드",
    "UNH": "유나이티드헬스",
    "ASML": "ASML",
    "PG": "프록터앤갬블",
    "COST": "코스트코",
    "JNJ": "존슨앤존슨",
    "ORCL": "오라클",
    "HD": "홈디포",
    "MRK": "머크",
    "ABBV": "애브비",
    "CVX": "셰브론",
    "AMD": "AMD",
    "KO": "코카콜라",
    "CRM": "세일즈포스",
    "PEP": "펩시코",
    "ADBE": "어도비",
    "NFLX": "넷플릭스",
    "TMO": "써모피셔",
    "WFC": "웰스파고",
    "BAC": "뱅크오브아메리카",
    "DIS": "디즈니",
    "QCOM": "퀄컴",
    "ACN": "액센츄어",
    "LIN": "린데",
    "INTC": "인텔",
    "VZ": "버라이즌",
    "CSCO": "시스코",
    "ABT": "애보트",
    "INTU": "인튜이트",
    "DHR": "다나허",
    "CAT": "캐터필러",
    "AMAT": "어플라이드머티어리얼즈",
    "TXN": "텍사스인스트루먼트",
    "PFE": "화이자",
    "IBM": "IBM",
    "UBER": "우버",
    "GE": "GE",
    "MS": "모건스탠리",
    "PM": "필립모리스",
    "NEE": "넥스트에라에너지",
    "AMGN": "암젠",
    "GS": "골드만삭스",
    "NOW": "서비스나우",
    "LOW": "로우스",
    "COP": "코노코필립스",
    "RTX": "레이시온",
    "HON": "하니웰",
    "LRCX": "램리서치",
    "PLTR": "팔란티어",
    "BLK": "블랙록",
    "AXP": "아메리칸익스프레스",
    "MU": "마이크론",
    "SCHW": "찰스슈왑",
    "T": "AT&T",
    "MDLZ": "몬델리즈",
    "DE": "디어앤컴퍼니",
    "SYK": "스트라이커",
    "TJX": "TJX",
    "BA": "보잉",
    "VRTX": "버텍스",
    "REGN": "리제네론",
    "SBUX": "스타벅스",
    "BKNG": "부킹홀딩스",
    "ADP": "ADP",
    "LMT": "록히드마틴",
    "BSX": "보스턴사이언티픽",
    "PLD": "프롤로지스",
    "MMC": "마시앤맥레넌",
    "ABNB": "에어비앤비",
    "C": "씨티그룹",
    "ZTS": "조에티스",
    "GILD": "길리어드",
    "CI": "시그나",
    "PANW": "팔로알토",
    "CVS": "CVS헬스",
    "ADI": "아날로그디바이스",
    "FI": "파이서브",
    "KLAC": "KLA",
    "ELV": "엘레반스헬스",
    "CDNS": "케이던스",
    "SNPS": "시놉시스",
    "WM": "웨이스트매니지먼트",
    "EOG": "EOG리소시즈",
    "SHW": "셔윈윌리엄스",
    "MO": "알트리아",
    "ICE": "ICE(인터컨티넨탈)",
    "HCA": "HCA헬스케어",
    "TGT": "타겟",
    "CL": "콜게이트",
    "MCK": "맥케슨",
    "PYPL": "페이팔",
    "NXPI": "NXP반도체",
    "CME": "CME그룹",
    "ORLY": "오라일리",
    "MAR": "메리어트",
    "FDX": "페덱스",
    "APH": "암페놀",
    "Eaton": "이튼",
    "EMR": "에머슨",
    "MCO": "무디스",
    "NOC": "노스롭그루먼",
    "ROP": "로퍼테크놀로지",
    "PH": "파커하니핀",
    "PSX": "필립스66",
    "MDT": "메드트로닉",
    "MRVL": "마벨테크",
    "SNOW": "스노우플레이크",
    "COF": "캐피탈원",
    "AZN": "아스트라제네카",
    "PDD": "핀둬둬(테무)",
    "BABA": "알리바바",
    "TM": "토요타",
    "NVO": "노보노디스크",
    "ASML": "ASML",
    "SAP": "SAP",
    "SONY": "소니",
    "SHOP": "쇼피파이",
    "SPOT": "스포티파이",
    "BIDU": "바이두",
    "LI": "리 오토",
    "NIO": "니오",
    "XPEV": "샤오펑",
    "TSM": "TSMC",
    "ARM": "ARM",
    "SMCI": "슈퍼마이크로",
    "AVGO": "브로드컴",
    "APP": "앱러빈",
    "U": "유니티",
    "SQ": "블록(스퀘어)",
    "AFRM": "어펌",
    "SOFI": "소파이",
    "NU": "누뱅크",
    "HOOD": "로빈후드",
    "COIN": "코인베이스",
    "MSTR": "마이크로스트래티지",
    "MBLY": "모빌아이",
    "LAZR": "루미나",
    "RIVN": "리비안",
    "LCID": "루시드",
    "DKNG": "드래프트킹스",
    "ROKU": "로쿠",
    "ZM": "줌",
    "DOCU": "도큐사인",
    "TEAM": "아틀라시안",
    "DDOG": "다타독",
    "MDB": "몽고DB",
    "OKTA": "옥타",
    "CRWD": "크라우드스트라이크",
    "ZS": "지스케일러",
    "NET": "클라우드플레어",
    "PATH": "유아이패스",
    "UNITY": "유니티",
    "SE": "씨(쇼피)",
    "MELI": "메르카도리브레",
    "CPNG": "쿠팡",
    "DASH": "도어대시",
    "ABNB": "에어비앤비",
    "LYFT": "리프트",
    "AAL": "아메리칸항공",
    "DAL": "델타항공",
    "UAL": "유나이티드항공",
    "LUV": "사우스웨스트항공",
    "CCL": "카니발",
    "RCL": "로열캐리비안",
    "NCLH": "노르웨이지안",
    "BKNG": "부킹홀딩스",
    "EXPE": "익스피디아",
    "TRIP": "트립어드바이저",
    "MAR": "메리어트",
    "HLT": "힐튼",
    "WYNN": "윈리조트",
    "LVS": "라스베이거스샌즈",
    "MGM": "MGM리조트",
    "AMC": "AMC엔터",
    "GME": "게임스탑",
    "KOSS": "코스",
    "BB": "블랙베리",
    "NOK": "노키아",
    "AI": "C3.ai",
    "SOUN": "사운드하운드",
    "BROS": "더치브로스",
    "CMG": "치폴레",
    "SHAK": "쉐이크쉑",
    "WING": "윙스탑",
    "DPZ": "도미노피자",
    "YUM": "얌브랜즈",
    "MCD": "맥도날드",
    "SBUX": "스타벅스",
    "NKE": "나이키",
    "LULU": "룰루레몬",
    "UA": "언더아머",
    "SKX": "스케쳐스",
    "CROX": "크록스",
    "DECK": "데커스(호카)",
    "ONON": "온홀딩",
    "TSLA": "테슬라",
    "F": "포드",
    "GM": "GM",
    "STLA": "스텔란티스",
    "HMC": "혼다",
    "TM": "토요타",
    "VALE": "발레",
    "RIO": "리오틴토",
    "BHP": "BHP",
    "FCX": "프리포트맥모란",
    "ALB": "알베말",
    "SQM": "SQM",
    "LAC": "리튬아메리카스",
    "MP": "MP머티어리얼스",
    "X": "US스틸",
    "CLF": "클리프스",
    "NUE": "뉴코어",
    "STLD": "스틸다이나믹스",
    "AA": "알코아",
    "PFE": "화이자",
    "MRNA": "모더나",
    "BNTX": "바이오엔텍",
    "NVAX": "노바백스",
    "JNJ": "존슨앤존슨",
    "LLY": "일라이릴리",
    "NVO": "노보노디스크",
    "MRK": "머크",
    "ABBV": "애브비",
    "BMY": "브리스톨마이어스",
    "GILD": "길리어드",
    "AMGN": "암젠",
    "REGN": "리제네론",
    "VRTX": "버텍스",
    "BIIB": "바이오젠",
    "IONQ": "아이온큐",
    "RGTI": "리게티",
    "QUBT": "퀀텀컴퓨팅",
    "PLTR": "팔란티어",
    "OKLO": "오클로",
    "SMR": "뉴스케일",
    "CCJ": "카메코",
    "VST": "비스트라",
    "CEG": "컨스텔레이션",
    "TLT": "20년물국채ETF",
    "TMF": "20년물국채3배ETF",
    "TLW": "20년물국채1배ETF",
    "SHY": "1-3년물국채ETF",
    "IEF": "7-10년물국채ETF",
    "SPY": "S&P500 ETF",
    "VOO": "S&P500 ETF(뱅가드)",
    "IVV": "S&P500 ETF(iShares)",
    "QQQ": "나스닥100 ETF",
    "TQQQ": "나스닥100 3배 ETF",
    "SQQQ": "나스닥100 인버스 3배 ETF",
    "QLD": "나스닥100 2배 ETF",
    "PSQ": "나스닥100 인버스 ETF",
    "SOXX": "반도체 ETF",
    "SOXL": "반도체 3배 ETF",
    "SOXS": "반도체 인버스 3배 ETF",
    "DIA": "다우존스 ETF",
    "IWM": "러셀2000 ETF",
    "ARKK": "아크이노베이션 ETF",
    "ARKW": "아크차세대인터넷 ETF",
    "ARKG": "아크게노믹 ETF",
    "ARKF": "아크핀테크 ETF",
    "SCHD": "배당성장 ETF(SCHD)",
    "JEPI": "커버드콜 ETF(JEPI)",
    "JEPQ": "나스닥 커버드콜 ETF(JEPQ)",
    "QYLD": "나스닥 커버드콜 ETF(QYLD)",
    "XYLD": "S&P500 커버드콜 ETF(XYLD)",
    "GLD": "금 ETF",
    "IAU": "금 ETF(iShares)",
    "SLV": "은 ETF",
    "USO": "원유 ETF",
    "UNG": "천연가스 ETF",
    "BITO": "비트코인선물 ETF",
    "IBIT": "비트코인현물 ETF(블랙록)",
    "FBTC": "비트코인현물 ETF(피델리티)",
    "ARKB": "비트코인현물 ETF(아크)",
    "TSLL": "테슬라 1.5/2배 ETF",
    "NVDL": "엔비디아 2배 ETF",
}

def get_kr_name(ticker, english_name):
    """티커에 해당하는 한국어 이름을 반환하거나, 영어 이름을 가공하여 반환."""
    # 1. 수동 매핑 리스트 확인
    if ticker in US_KR_NAME_MAP:
        return US_KR_NAME_MAP[ticker]
    
    # 2. 영어 이름 가공 (Suffix 제거)
    import re
    cleaned = re.sub(r'\s+(Inc|Corp|Ltd|S\.A\.|plc|Group|Holdings|Co|Company|Incorporated|Corporation|Limited|Plc|L\.P\.)(\.|\b).*', '', english_name, flags=re.I)
    cleaned = cleaned.strip()
    
    # 너무 길면 자름
    if len(cleaned) > 25:
        cleaned = cleaned[:24] + ".."
        
    return cleaned
